### PR TITLE
Fix onConnect race condition

### LINKED ISSUE #321: Race condition: onMessage() can be called before onConnect()
There is a subtle but nasty race condition bug in the Agent base class. onConnect() is the only place where you get connection context to do things like serialize session or identity information as an attachment (so it survives hibernation) to the connection for later use in access control. However, it's possible for onMessage() to be called BEFORE onConnect(). I have worked around it for now by queuing up messages and only processing the queue at the end of my onConnect() method but it's a footgun that others will hit.

I'm prepared to investigate and submit a pull request if I can figure out how to fix it. This should be possible because at the very least I can move my message queuing approach to the Agent base class, but before I do that, I'm wondering if its a known issue and if anyone else has any thoughts.

Also, I'm wondering if I should fix it in the Agent source code and if so, where is the source of truth for that? Alternatively, maybe it's a problem with PartyKit and I should fix it there?

### PR DESCRIPTION
**Pull request by deathbyknowledge**
Fixes #321 and adds test for message ordering.

### CODE REVIEW

**Comment by whoiskatrin** [comment]
tentatively looks ok to me

File: packages/agents/src/tests/worker.ts [hunk 1]
```diff
@@ -105,6 +129,13 @@ export default {
       return new Response("Internal Server Error", { status: 500 });
     }
 
+    if (url.pathname.startsWith("/agents/")) {
+      return (
+        (await routeAgentRequest(request, env)) ||
+        new Response("Not found", { status: 404 })
+      );
+    }
+
```
Comment (threepointone) [inline packages/agents/src/tests/worker.ts]:
```suggestion    
    return (
      (await routeAgentRequest(request, env)) ||
      new Response("Not found", { status: 404 })
    );    

```
