### PR TITLE
pipe SQL errors into the existing onError method using a new SqlError class

### LINKED ISSUE #767: Allow customizing logger for SQL errors
## Problem

The `sql` method in `Agent` uses `console.error` directly for logging SQL errors:

```typescript
} catch (e) {
  console.error(`failed to execute sql query: ${query}`, e);
  throw this.onError(e);
}
```

This bypasses any structured logging the application may have configured. During DO resets (e.g., code deployments), this produces unstructured logs like:

```
(error) failed to execute sql query:
    INSERT OR REPLACE INTO cf_agents_state (id, state)
    VALUES (?, ?)
   Error: Durable Object reset because its code was updated.
```

## Proposal

Allow users to customize logging behavior, either via:

1. **Override method** - `onSqlError(query: string, error: unknown)` that defaults to `console.error` but can be overridden
2. **Logger injection** - Accept a logger in Agent options/constructor
3. **Use observability** - Route through the existing `observability` interface

Option 1 is minimal and consistent with existing patterns like `onError`.

### PR DESCRIPTION
**Pull request by whoiskatrin**
Instead of adding a separate onSqlError hook, I implemented a cleaner approach (suggested by @threepointone) that pipes SQL errors into the existing onError method using a new SqlError class

Fixes #767

### CODE REVIEW

File: packages/agents/src/index.ts [hunk 1]
```diff
@@ -391,7 +391,7 @@ export class Agent<
       // Execute the SQL query with the provided values
       return [...this.ctx.storage.sql.exec(query, ...values)] as T[];
     } catch (e) {
-      console.error(`failed to execute sql query: ${query}`, e);
```
Comment (threepointone) [inline packages/agents/src/index.ts:394]: instead why don't we use our logger directly here?

Comment (threepointone) [reply packages/agents/src/index.ts:394]: or pipe into onError

Comment (whoiskatrin) [reply packages/agents/src/index.ts:394]: agree with piping, done that
